"""One-off: extract 2026 BAH E-5 w/ dependents from PDF -> bah_rates_2026_data.py"""
from __future__ import annotations

import re
from pathlib import Path

import pdfplumber

# Prefer PDF in repo `data/`; fall back to argv or legacy path
_REPO_PDF = Path(__file__).resolve().parent.parent / "data" / "2026 BAH Rates.pdf"
_LEGACY_PDF = Path(
    r"c:\Users\jorda\AppData\Roaming\Cursor\User\workspaceStorage"
    r"\79a28b12eb9a03ef2980284272938111\pdfs\d4842ccb-b1b3-49aa-99a4-af2e66ed3504"
    r"\2026 BAH Rates.pdf"
)
DEFAULT_PDF = _REPO_PDF if _REPO_PDF.is_file() else _LEGACY_PDF

code_re = re.compile(r"^([A-Z]{2}\d{3})\s+")


def parse_line(line: str):
    line = line.strip()
    if not code_re.match(line):
        return None
    m = code_re.match(line)
    code = m.group(1)
    rest = line[m.end() :].strip()
    parts = rest.split()
    name_parts: list[str] = []
    numbers: list[int] = []
    for p in parts:
        if p.isdigit():
            numbers.append(int(p))
        elif numbers:
            break
        else:
            name_parts.append(p)
    if len(numbers) < 5:
        return None
    e05 = numbers[4]
    name = " ".join(name_parts).strip()
    return code, name, e05


def main() -> None:
    import sys

    pdf_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_PDF
    out_path = Path(__file__).resolve().parent.parent / "src" / "veteran_education_financial_readiness" / "bah_rates_2026_data.py"

    seen: dict[str, tuple[str, int]] = {}
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            text = page.extract_text()
            if not text:
                continue
            lines = text.splitlines()
            header = lines[0] if lines else ""
            if "WITHOUT DEPENDENTS" in header:
                continue
            if "WITH DEPENDENTS" not in header:
                continue
            for line in lines:
                parsed = parse_line(line)
                if not parsed:
                    continue
                code, name, e05 = parsed
                if code in seen and seen[code][1] != e05:
                    raise SystemExit(f"Mismatch {code}: {seen[code]} vs {(name, e05)}")
                seen[code] = (name, e05)

    items = sorted(seen.items(), key=lambda x: (x[1][0].upper(), x[0]))

    lines = [
        '"""2026 BAH with dependents — E-5 monthly rate by MHA (from DoD table)."""',
        "# Auto-generated by scripts/extract_bah_2026.py — do not hand-edit.",
        "",
        "BAH_YEAR_LABEL = \"2026\"",
        "BAH_GRADE = \"E-05\"",
        "BAH_DEPENDENTS = \"with dependents\"",
        "",
        "# MHA code -> (display_name, e05_monthly_usd)",
        "BAH_E05_WITH_DEP: dict[str, tuple[str, int]] = {",
    ]
    for code, (name, e05) in items:
        safe_name = name.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    "{code}": ("{safe_name}", {e05}),')
    lines.append("}")
    lines.append("")
    lines.extend(
        [
            "",
            "def _display_name(mha_code: str, raw_name: str) -> str:",
            '    """City/state style label without MHA code; disambiguate duplicate county-group rows."""',
            '    if mha_code.startswith("ZZ") and raw_name.strip().upper() == "COUNTY COST GROUP":',
            "        return f\"{raw_name} {int(mha_code[2:])}\"",
            "    return raw_name",
            "",
            "",
            "_DISPLAY_TO_CODE: dict[str, str] = {}",
            "for _code, (_name, _) in BAH_E05_WITH_DEP.items():",
            "    _label = _display_name(_code, _name)",
            "    if _label in _DISPLAY_TO_CODE:",
            '        raise RuntimeError(f"Duplicate BAH display label: {_label!r}")',
            "    _DISPLAY_TO_CODE[_label] = _code",
            "",
            "",
            "def list_location_labels() -> list[str]:",
            '    """Sorted labels for selectbox (city / area only, no MHA code)."""',
            "    return sorted(_DISPLAY_TO_CODE.keys(), key=lambda s: s.upper())",
            "",
            "",
            "def label_to_code(label: str) -> str:",
            '    """Map selectbox label back to MHA code."""',
            "    try:",
            "        return _DISPLAY_TO_CODE[label]",
            "    except KeyError as e:",
            '        raise ValueError("Invalid location label") from e',
            "",
        ]
    )
    lines.append(
        "def e05_rate_for_code(mha_code: str) -> int:"
        '\n    return BAH_E05_WITH_DEP[mha_code][1]'
        "\n"
    )

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(items)} locations to {out_path}")


if __name__ == "__main__":
    main()
